-- 1. Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  
  -- Custom witchy fields
  moon_phase text, 
  coven_name text,

  constraint username_length check (char_length(username) >= 3)
);

-- 2. Enable Row Level Security (RLS)
-- This turns on the security system so random people can't delete your data.
alter table profiles enable row level security;

-- 3. Create Policy: "Public profiles are viewable by everyone."
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

-- 4. Create Policy: "Users can insert their own profile."
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

-- 5. Create Policy: "Users can update own profile."
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

  -- 1. Create a function that inserts a row into public.profiles
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, full_name)
  values (
    new.id, 
    new.email, -- defaults username to email initially
    new.raw_user_meta_data ->> 'full_name'
  );
  return new;
end;
$$;

-- 2. Create the trigger to fire that function every time a user signs up
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

  -- 1. ADD ROLES TO PROFILES
-- We add a 'role' column. Default is 'initiate' (non-verified).
-- Future values could be: 'verified', 'supporter', 'admin'.
ALTER TABLE public.profiles 
ADD COLUMN role text default 'initiate';

-- 2. CREATE POSTS TABLE
create table public.posts (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  image_url text, -- Optional image for the post
  
  -- Link the post to the User who wrote it
  user_id uuid references public.profiles(id) not null
);

-- 3. ENABLE SECURITY (RLS)
alter table public.posts enable row level security;

-- 4. POLICIES
-- Everyone can SEE posts
create policy "Public posts are viewable by everyone."
  on public.posts for select
  using ( true );

-- Only Logged In users can CREATE posts
create policy "Authenticated users can insert posts"
  on public.posts for insert
  with check ( auth.uid() = user_id );

-- Users can only DELETE their OWN posts
create policy "Users can delete own posts"
  on public.posts for delete
  using ( auth.uid() = user_id );

  -- 1. Add a handle column
ALTER TABLE public.profiles 
ADD COLUMN handle text unique;

-- 2. Populate existing handles (temporary fix for existing users)
-- This just takes their username and makes it lowercase.
UPDATE public.profiles 
SET handle = lower(replace(username, ' ', '-'));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, handle, full_name)
  values (
    new.id, 
    -- 1. Get the username passed from the Sign Up form
    new.raw_user_meta_data ->> 'username',
    -- 2. Get the handle passed (or generate one if missing)
    new.raw_user_meta_data ->> 'handle',
    -- 3. Full name if provided
    new.raw_user_meta_data ->> 'full_name'
  );
  return new;
end;
$$;

  -- Create a table for Tarot Cards
create table tarot_cards (
  id bigint generated by default as identity primary key,
  name text not null,
  suit text, -- 'Wands', 'Cups', 'Swords', 'Pentacles', or null for Major Arcana
  arcana_type text not null, -- 'Major' or 'Minor'
  meaning_upright text,
  meaning_reversed text,
  description text,
  image_url text -- Optional: You can add links to card images later
);

-- Enable Row Level Security (RLS) so everyone can READ, but only you can WRITE
alter table tarot_cards enable row level security;

create policy "Tarot cards are viewable by everyone"
  on tarot_cards for select
  using ( true );

ALTER TABLE tarot_cards
  ADD COLUMN element TEXT,
  ADD COLUMN astrology TEXT,
  ADD COLUMN numerical_keyword TEXT;

-- 1. INSERT MAJOR ARCANA
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('The Fool', NULL, 'Major', 'Beginnings, innocence, spontaneity, free spirit', 'Hesitation, reckless choices, risk without thought', NULL, 'Air', 'Uranus', '0 — Infinite potential'),
('The Magician', NULL, 'Major', 'Manifestation, resourcefulness, inspired action', 'Manipulation, unused potential, deception', NULL, 'Air', 'Mercury', '1 — Action, willpower'),
('The High Priestess', NULL, 'Major', 'Intuition, subconscious knowledge, mystery', 'Secrets, disconnection, blocked intuition', NULL, 'Water', 'Moon', '2 — Duality, hidden truths'),
('The Empress', NULL, 'Major', 'Abundance, nurturing, creativity, fertility', 'Dependence, creative blocks, smothering energy', NULL, 'Earth', 'Venus', '3 — Growth, creation'),
('The Emperor', NULL, 'Major', 'Authority, structure, discipline, power', 'Tyranny, rigidity, lack of control', NULL, 'Fire', 'Aries', '4 — Stability, foundation'),
('The Hierophant', NULL, 'Major', 'Tradition, spiritual wisdom, conformity', 'Rebellion, challenge of norms, personal beliefs', NULL, 'Earth', 'Taurus', '5 — Teaching, structure'),
('The Lovers', NULL, 'Major', 'Love, harmony, choices, alignment', 'Imbalance, disharmony, difficult choices', NULL, 'Air', 'Gemini', '6 — Union, relationships'),
('The Chariot', NULL, 'Major', 'Willpower, victory, determination', 'Lack of control, scattered energy, defeat', NULL, 'Water', 'Cancer', '7 — Direction, mastery'),
('Strength', NULL, 'Major', 'Inner strength, courage, compassion', 'Self-doubt, insecurity, weakness', NULL, 'Fire', 'Leo', '8 — Power, resilience'),
('The Hermit', NULL, 'Major', 'Soul-searching, introspection, solitude', 'Isolation, loneliness, distraction', NULL, 'Earth', 'Virgo', '9 — Wisdom, searching'),
('Wheel of Fortune', NULL, 'Major', 'Luck, fate, cycles, turning point', 'Bad luck, resistance to change', NULL, 'Fire', 'Jupiter', '10 — Change, destiny'),
('Justice', NULL, 'Major', 'Truth, fairness, law, cause and effect', 'Unfairness, dishonesty, imbalance', NULL, 'Air', 'Libra', '11 — Balance, truth'),
('The Hanged Man', NULL, 'Major', 'Sacrifice, release, new perspective', 'Stagnation, delay, refusal to let go', NULL, 'Water', 'Neptune', '12 — Surrender, pause'),
('Death', NULL, 'Major', 'Transformation, endings, transition', 'Resistance to change, stagnation', NULL, 'Water', 'Scorpio', '13 — Rebirth, cycles'),
('Temperance', NULL, 'Major', 'Balance, moderation, harmony', 'Imbalance, excess, conflict', NULL, 'Fire', 'Sagittarius', '14 — Healing, blending'),
('The Devil', NULL, 'Major', 'Bondage, addiction, temptation', 'Release, freedom, detachment', NULL, 'Earth', 'Capricorn', '15 — Shadow self'),
('The Tower', NULL, 'Major', 'Sudden change, upheaval, revelation', 'Avoidance, fear of change, delay', NULL, 'Fire', 'Mars', '16 — Ruin, awakening'),
('The Star', NULL, 'Major', 'Hope, inspiration, renewal', 'Despair, lack of faith, discouragement', NULL, 'Air', 'Aquarius', '17 — Guidance, clarity'),
('The Moon', NULL, 'Major', 'Illusion, fear, subconscious', 'Clarity, truth revealed, release of fear', NULL, 'Water', 'Pisces', '18 — Dreams, intuition'),
('The Sun', NULL, 'Major', 'Joy, success, vitality, positivity', 'Temporary sadness, lack of clarity', NULL, 'Fire', 'Sun', '19 — Radiance, growth'),
('Judgement', NULL, 'Major', 'Awakening, renewal, purpose', 'Self-doubt, stagnation, ignoring calling', NULL, 'Fire', 'Pluto', '20 — Reckoning, truth'),
('The World', NULL, 'Major', 'Completion, wholeness, accomplishment', 'Incomplete goals, delays, stagnation', NULL, 'Earth', 'Saturn', '21 — Completion, mastery');

-- 2. INSERT WANDS
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('Ace of Wands', 'Wands', 'Minor', 'Inspiration, creation, new energy', 'Delays, lack of direction', NULL, 'Fire', 'Aries/Leo/Sagittarius', '1 — Potential'),
('Two of Wands', 'Wands', 'Minor', 'Planning, decisions, future vision', 'Fear of change, bad planning', NULL, 'Fire', 'Mars in Aries', '2 — Duality'),
('Three of Wands', 'Wands', 'Minor', 'Expansion, foresight, progress', 'Delays, obstacles, disappointment', NULL, 'Fire', 'Sun in Aries', '3 — Growth'),
('Four of Wands', 'Wands', 'Minor', 'Celebration, harmony, home', 'Conflict at home, instability', NULL, 'Fire', 'Venus in Aries', '4 — Stability'),
('Five of Wands', 'Wands', 'Minor', 'Conflict, competition, tension', 'Avoiding conflict, inner tension', NULL, 'Fire', 'Saturn in Leo', '5 — Struggle'),
('Six of Wands', 'Wands', 'Minor', 'Victory, success, recognition', 'Ego, fall from grace, delays', NULL, 'Fire', 'Jupiter in Leo', '6 — Triumph'),
('Seven of Wands', 'Wands', 'Minor', 'Defense, perseverance', 'Exhaustion, giving up', NULL, 'Fire', 'Mars in Leo', '7 — Challenge'),
('Eight of Wands', 'Wands', 'Minor', 'Movement, fast action', 'Delays, frustration', NULL, 'Fire', 'Mercury in Sagittarius', '8 — Acceleration'),
('Nine of Wands', 'Wands', 'Minor', 'Resilience, boundaries', 'Paranoia, overwhelm', NULL, 'Fire', 'Moon in Sagittarius', '9 — Persistence'),
('Ten of Wands', 'Wands', 'Minor', 'Burden, hard work', 'Burnout, release needed', NULL, 'Fire', 'Saturn in Sagittarius', '10 — Completion'),
('Page of Wands', 'Wands', 'Minor', 'Exploration, enthusiasm', 'Lack of direction, immaturity', NULL, 'Fire', 'Fire Signs', 'Youthful Fire'),
('Knight of Wands', 'Wands', 'Minor', 'Action, passion, adventure', 'Recklessness, impatience', NULL, 'Fire', 'Fire Signs', 'Young Fire'),
('Queen of Wands', 'Wands', 'Minor', 'Confidence, determination', 'Jealousy, insecurity', NULL, 'Fire', 'Aries', 'Mature Fire'),
('King of Wands', 'Wands', 'Minor', 'Leadership, vision', 'Impulsiveness, domineering', NULL, 'Fire', 'Leo', 'Mastery of Fire');

-- 3. INSERT CUPS
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('Ace of Cups', 'Cups', 'Minor', 'Love, new feelings, compassion', 'Blocked emotions, emptiness', NULL, 'Water', 'Cancer/Scorpio/Pisces', '1 — Emotional potential'),
('Two of Cups', 'Cups', 'Minor', 'Union, partnership, connection', 'Breakup, imbalance', NULL, 'Water', 'Venus in Cancer', '2 — Unity'),
('Three of Cups', 'Cups', 'Minor', 'Friendship, community', 'Overindulgence, isolation', NULL, 'Water', 'Mercury in Cancer', '3 — Community'),
('Four of Cups', 'Cups', 'Minor', 'Apathy, contemplation', 'Awareness, acceptance', NULL, 'Water', 'Moon in Cancer', '4 — Withdrawal'),
('Five of Cups', 'Cups', 'Minor', 'Grief, disappointment', 'Acceptance, healing', NULL, 'Water', 'Mars in Scorpio', '5 — Loss'),
('Six of Cups', 'Cups', 'Minor', 'Nostalgia, innocence', 'Stuck in past, naivety', NULL, 'Water', 'Sun in Scorpio', '6 — Memory'),
('Seven of Cups', 'Cups', 'Minor', 'Choices, fantasy, illusion', 'Clarity, groundedness', NULL, 'Water', 'Venus in Scorpio', '7 — Illusion'),
('Eight of Cups', 'Cups', 'Minor', 'Walking away, deeper purpose', 'Avoidance, fear of change', NULL, 'Water', 'Saturn in Pisces', '8 — Departure'),
('Nine of Cups', 'Cups', 'Minor', 'Contentment, satisfaction', 'Greed, dissatisfaction', NULL, 'Water', 'Jupiter in Pisces', '9 — Fulfillment'),
('Ten of Cups', 'Cups', 'Minor', 'Harmony, bliss, family', 'Disconnection, misalignment', NULL, 'Water', 'Mars in Pisces', '10 — Emotional completion'),
('Page of Cups', 'Cups', 'Minor', 'Creativity, curiosity', 'Emotional immaturity', NULL, 'Water', 'Water Signs', 'Youthful Water'),
('Knight of Cups', 'Cups', 'Minor', 'Romance, idealism', 'Moodiness, unrealistic', NULL, 'Water', 'Water Signs', 'Young Water'),
('Queen of Cups', 'Cups', 'Minor', 'Compassion, intuition', 'Codependency', NULL, 'Water', 'Cancer', 'Mature Water'),
('King of Cups', 'Cups', 'Minor', 'Balance, wisdom, control', 'Coldness, manipulation', NULL, 'Water', 'Scorpio', 'Mastery of Water');

-- 4. INSERT SWORDS
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('Ace of Swords', 'Swords', 'Minor', 'Breakthrough, clarity', 'Confusion, chaos', NULL, 'Air', 'Gemini/Libra/Aquarius', '1 — Mental clarity'),
('Two of Swords', 'Swords', 'Minor', 'Indecision, stalemate', 'Truth revealed, decision made', NULL, 'Air', 'Moon in Libra', '2 — Block'),
('Three of Swords', 'Swords', 'Minor', 'Heartbreak, grief', 'Recovery, forgiveness', NULL, 'Air', 'Saturn in Libra', '3 — Pain'),
('Four of Swords', 'Swords', 'Minor', 'Rest, restoration', 'Burnout, restlessness', NULL, 'Air', 'Jupiter in Libra', '4 — Recovery'),
('Five of Swords', 'Swords', 'Minor', 'Conflict, betrayal', 'Resolution, compromise', NULL, 'Air', 'Venus in Aquarius', '5 — Defeat'),
('Six of Swords', 'Swords', 'Minor', 'Transition, healing', 'Trouble, resistance', NULL, 'Air', 'Mercury in Aquarius', '6 — Passage'),
('Seven of Swords', 'Swords', 'Minor', 'Deception, strategy', 'Confession, truth', NULL, 'Air', 'Moon in Aquarius', '7 — Strategy'),
('Eight of Swords', 'Swords', 'Minor', 'Restriction, fear', 'Freedom, release', NULL, 'Air', 'Jupiter in Gemini', '8 — Limitation'),
('Nine of Swords', 'Swords', 'Minor', 'Anxiety, worry', 'Relief, hope', NULL, 'Air', 'Mars in Gemini', '9 — Despair'),
('Ten of Swords', 'Swords', 'Minor', 'Endings, collapse', 'Recovery, regeneration', NULL, 'Air', 'Sun in Gemini', '10 — Finality'),
('Page of Swords', 'Swords', 'Minor', 'Curiosity, new ideas', 'Deception, manipulation', NULL, 'Air', 'Air Signs', 'Youthful Air'),
('Knight of Swords', 'Swords', 'Minor', 'Speed, ambition', 'Aggression, recklessness', NULL, 'Air', 'Air Signs', 'Young Air'),
('Queen of Swords', 'Swords', 'Minor', 'Independence, clarity', 'Coldness, bitterness', NULL, 'Air', 'Libra', 'Mature Air'),
('King of Swords', 'Swords', 'Minor', 'Discipline, truth', 'Manipulation, cruelty', NULL, 'Air', 'Aquarius', 'Mastery of Air');

-- 5. INSERT PENTACLES
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('Ace of Pentacles', 'Pentacles', 'Minor', 'Opportunity, prosperity', 'Lost opportunity', NULL, 'Earth', 'Taurus/Virgo/Capricorn', '1 — Material potential'),
('Two of Pentacles', 'Pentacles', 'Minor', 'Balance, adaptability', 'Disorganization', NULL, 'Earth', 'Jupiter in Capricorn', '2 — Balance'),
('Three of Pentacles', 'Pentacles', 'Minor', 'Teamwork, mastery', 'Disharmony', NULL, 'Earth', 'Mars in Capricorn', '3 — Collaboration'),
('Four of Pentacles', 'Pentacles', 'Minor', 'Security, control', 'Greed, releasing control', NULL, 'Earth', 'Sun in Capricorn', '4 — Possession'),
('Five of Pentacles', 'Pentacles', 'Minor', 'Poverty, hardship', 'Recovery, assistance', NULL, 'Earth', 'Mercury in Taurus', '5 — Loss'),
('Six of Pentacles', 'Pentacles', 'Minor', 'Generosity, giving', 'Strings attached', NULL, 'Earth', 'Moon in Taurus', '6 — Exchange'),
('Seven of Pentacles', 'Pentacles', 'Minor', 'Patience, investment', 'Impatience, waste', NULL, 'Earth', 'Saturn in Taurus', '7 — Evaluation'),
('Eight of Pentacles', 'Pentacles', 'Minor', 'Skill, hard work', 'Perfectionism, lack of focus', NULL, 'Earth', 'Sun in Virgo', '8 — Work'),
('Nine of Pentacles', 'Pentacles', 'Minor', 'Luxury, self-sufficiency', 'Overinvestment', NULL, 'Earth', 'Venus in Virgo', '9 — Reward'),
('Ten of Pentacles', 'Pentacles', 'Minor', 'Wealth, family legacy', 'Financial failure', NULL, 'Earth', 'Mercury in Virgo', '10 — Legacy'),
('Page of Pentacles', 'Pentacles', 'Minor', 'Ambition, opportunity', 'Procrastination', NULL, 'Earth', 'Earth Signs', 'Youthful Earth'),
('Knight of Pentacles', 'Pentacles', 'Minor', 'Routine, efficiency', 'Laziness, stagnation', NULL, 'Earth', 'Earth Signs', 'Young Earth'),
('Queen of Pentacles', 'Pentacles', 'Minor', 'Practicality, comfort', 'Smothering, jealousy', NULL, 'Earth', 'Capricorn', 'Mature Earth'),
('King of Pentacles', 'Pentacles', 'Minor', 'Abundance, control', 'Greed, stubbornness', NULL, 'Earth', 'Taurus', 'Mastery of Earth');

create table user_daily_tarot (
  user_id uuid references auth.users not null primary key,
  
  -- Logic for the 3-Card Spread Page
  spread_date date, -- The date this spread was drawn
  spread_card_ids bigint[], -- Array of 3 IDs drawn for the spread
  
  -- Logic for the Widget (Deck draining)
  widget_date date, -- The date the widget deck was last touched
  widget_drawn_ids bigint[], -- Array of IDs ALREADY drawn today
  
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table user_daily_tarot enable row level security;

-- Policy: Users can only read/update their own data
create policy "Users can view own tarot data" on user_daily_tarot
  for select using (auth.uid() = user_id);

create policy "Users can update own tarot data" on user_daily_tarot
  for update using (auth.uid() = user_id);

create policy "Users can insert own tarot data" on user_daily_tarot
  for insert with check (auth.uid() = user_id);

/** * TABLE: SPELLS
* Description: Stores user grimoire entries.
* Features: 
* - Private Mode (User only)
* - Public Profile Mode (Visible on Profile)
* - Community Mode (Visible in Library)
*/

-- 1. Create the Table
CREATE TABLE public.spells (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  
  -- Foreign Key to Auth Users (Owner)
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  
  -- Core Data
  title text NOT NULL,
  intent text,         -- e.g. "Protection", "Love"
  ingredients text,    -- e.g. "Salt, Candle"
  moon_phase text,     -- e.g. "Waxing", "Full"
  content text,        -- The ritual steps
  
  -- Visibility Flags
  is_private boolean DEFAULT true,    -- If true, only Owner can see
  is_published boolean DEFAULT false, -- If true, shows up in Global Library
  
  -- Timestamps
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Add Foreign Key Constraint for Profiles
-- This allows us to fetch Author Name/Avatar when querying spells
ALTER TABLE public.spells
ADD CONSTRAINT spells_user_id_profiles_fkey
FOREIGN KEY (user_id)
REFERENCES public.profiles(id)
ON DELETE CASCADE;

-- 3. Enable Security
ALTER TABLE public.spells ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies

-- Policy A: VIEWING Spells
-- Logic: You can see the spell IF:
-- 1. You are the owner (auth.uid() = user_id)
-- 2. OR the spell is NOT private (is_private = false)
--    (This covers both "Profile Only" and "Community" spells)
CREATE POLICY "Public or Owner can view spells"
ON public.spells FOR SELECT
USING ( 
  auth.uid() = user_id 
  OR 
  is_private = false 
);

-- Policy B: INSERTING Spells
-- Logic: Users can only create spells for themselves
CREATE POLICY "Users can insert own spells"
ON public.spells FOR INSERT
WITH CHECK ( auth.uid() = user_id );

-- Policy C: UPDATING Spells
-- Logic: Users can only edit their own spells
CREATE POLICY "Users can update own spells"
ON public.spells FOR UPDATE
USING ( auth.uid() = user_id );

-- Policy D: DELETING Spells
-- Logic: Users can only delete their own spells
CREATE POLICY "Users can delete own spells"
ON public.spells FOR DELETE
USING ( auth.uid() = user_id );


-- 5. Profile Visibility Helper
-- Ensure profiles are visible so the "Scribed By" badge works
CREATE POLICY "Public profiles are viewable by everyone"
ON public.profiles FOR SELECT
USING ( true );

-- Create a table for Altar Items
create table altar_items (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  
  item_type text not null, -- 'candle', 'crystal', 'incense'
  variant text, -- 'white_candle', 'amethyst', etc.
  
  position_x integer default 50, -- For future drag-and-drop (percentage 0-100)
  position_y integer default 50, -- For future drag-and-drop
  
  active_since timestamp with time zone, -- When the candle was lit
  duration_minutes integer, -- How long it lasts (e.g., 1440 for 24 hours)
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table altar_items enable row level security;

-- Policies
create policy "Users can manage own altar" on altar_items
  for all using (auth.uid() = user_id);

-- 1. Create a new public bucket called 'avatars'
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true);

-- 2. Allow Public Access to View Avatars
-- This allows anyone (even guests) to see profile pictures
CREATE POLICY "Avatar images are publicly accessible."
ON storage.objects FOR SELECT
USING ( bucket_id = 'avatars' );

-- 3. Allow Authenticated Users to Upload
-- This restricts uploads to logged-in users. 
-- The (storage.foldername(name))[1] syntax ensures they can only upload to a folder matching their UUID.
CREATE POLICY "Anyone can upload an avatar."
ON storage.objects FOR INSERT
WITH CHECK ( 
  bucket_id = 'avatars' 
  AND auth.role() = 'authenticated'
);

-- 4. Allow Users to Update their own Avatar
CREATE POLICY "Anyone can update their own avatar."
ON storage.objects FOR UPDATE
USING ( 
  bucket_id = 'avatars' 
  AND auth.uid() = owner
);

-- 5. Allow Users to Delete their own Avatar
CREATE POLICY "Anyone can delete their own avatar."
ON storage.objects FOR DELETE
USING ( 
  bucket_id = 'avatars' 
  AND auth.uid() = owner
);

-- Create a new public bucket for post images
-- 1. Create the bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('post_images', 'post_images', true);


-- 2. Policy: Public Viewing
-- Anyone can view images in this bucket
CREATE POLICY "Post images are public"
ON storage.objects FOR SELECT
USING ( bucket_id = 'post_images' );


-- 3. Policy: Authenticated Uploads
-- Only logged-in users can upload.
-- They must upload to a folder matching their user ID to keep things organized.
CREATE POLICY "Users can upload their own post images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'post_images' 
  AND auth.role() = 'authenticated'
  AND (storage.foldername(name))[1] = auth.uid()::text
);


-- 4. Policy: Owner Delete
-- Users can only delete images located in their own folder.
CREATE POLICY "Users can delete their own post images"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'post_images' 
  AND auth.uid() = owner
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Crystal database
-- Add a column for the user's personal photo of the crystal
alter table public.user_crystal_collection 
add column user_image_url text;
-- 1. Create the Master Crystals Table
create table public.crystals (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  meaning text not null,
  element text not null, -- e.g., 'Earth', 'Water', 'Fire', 'Air', 'Spirit'
  color text not null,   -- Hex code for UI styling (e.g., '#9966CC')
  image_url text,        -- Optional: URL to an image in Supabase Storage
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create the Collection (Join) Table
create table public.user_crystal_collection (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  crystal_id uuid references public.crystals(id) on delete cascade not null,
  acquired_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Constraint: A user can only have one entry per crystal type
  unique(user_id, crystal_id)
);

-- 2.2. Add the two boolean flags
-- 'is_owned': True means they have it in their Satchel. Default true for existing rows.
alter table public.user_crystal_collection 
add column is_owned boolean not null default true;

-- 'is_wishlisted': True means they want it. Default false.
alter table public.user_crystal_collection 
add column is_wishlisted boolean not null default false;

-- 2.3. Add a constraint to prevent "Ghost Rows"
-- (A row shouldn't exist if the user neither owns nor wishlists it)
alter table public.user_crystal_collection
add constraint check_valid_entry 
check (is_owned = true or is_wishlisted = true);

-- 2.4. Identify and remove duplicates, keeping the most recently updated one
delete from public.user_crystal_collection a
using public.user_crystal_collection b
where a.id < b.id
  and a.user_id = b.user_id
  and a.crystal_id = b.crystal_id;

-- 2.5. NOW, verify/add the Unique Constraint
-- This ensures that 'upsert' updates the EXISTING row instead of creating a new one
alter table public.user_crystal_collection
drop constraint if exists user_crystal_collection_user_id_crystal_id_key; -- drop if exists just in case

alter table public.user_crystal_collection
add constraint user_crystal_collection_user_id_crystal_id_key
unique (user_id, crystal_id);

-- 3. Enable Row Level Security (RLS)
alter table public.crystals enable row level security;
alter table public.user_crystal_collection enable row level security;

-- 4. Create Policies

-- Crystals: Everyone can read, only service_role (admins) can write
create policy "Crystals are viewable by everyone" 
on public.crystals for select 
using ( true );

-- Collection: Users can view their own collection
create policy "Users can view their own collection" 
on public.user_crystal_collection for select 
using ( auth.uid() = user_id );

-- Collection: Users can insert into their own collection
create policy "Users can add to their own collection" 
on public.user_crystal_collection for insert 
with check ( auth.uid() = user_id );

-- Collection: Users can remove from their own collection
create policy "Users can remove from their own collection" 
on public.user_crystal_collection for delete 
using ( auth.uid() = user_id );

-- 1. Enable users to UPDATE their own rows (Fixes the "Can't alter" bug)
create policy "Users can update their own collection"
on public.user_crystal_collection for update
using ( auth.uid() = user_id )
with check ( auth.uid() = user_id );

-- 2. Ensure the unique constraint is correct (Prevent duplicates)
alter table public.user_crystal_collection
drop constraint if exists user_crystal_collection_user_id_crystal_id_key;

alter table public.user_crystal_collection
add constraint user_crystal_collection_user_id_crystal_id_key
unique (user_id, crystal_id);

-- Seeding some crystals
insert into public.crystals (name, meaning, element, color)
values
  (
    'Amethyst', 
    'Protects against psychic attack, relieves stress, and enhances spiritual awareness.', 
    'Air', 
    '#9966CC'
  ),
  (
    'Rose Quartz', 
    'The stone of universal love. Restores trust and harmony in relationships.', 
    'Earth', 
    '#F7C6C7'
  ),
  (
    'Clear Quartz', 
    'The master healer. Amplifies energy and thought, as well as the effect of other crystals.', 
    'Spirit', 
    '#E6E6E6'
  ),
  (
    'Black Tourmaline', 
    'Powerful protection against negative energy and electromagnetic smog.', 
    'Earth', 
    '#000000'
  ),
  (
    'Citrine', 
    'Attracts wealth, prosperity, and success. Imparts joy and enthusiasm.', 
    'Fire', 
    '#E4D00A'
  ),
  (
    'Selenite', 
    'Provides clarity of mind and cleanses negative energy from other stones.', 
    'Air', 
    '#FFFFFF'
  ),
  (
    'Lapis Lazuli', 
    'Encourages self-awareness, allows self-expression and reveals inner truth.', 
    'Water', 
    '#26619C'
  ),
  (
    'Carnelian', 
    'Restores vitality and motivation, and stimulates creativity.', 
    'Fire', 
    '#B31B1B'
  ),
  (
    'Tiger''s Eye', 
    'A stone of protection that may also bring good luck to the wearer.', 
    'Fire', 
    '#E08D3C'
  ),
  (
    'Moonstone', 
    'A stone of new beginnings. Promotes intuition and empathy.', 
    'Water', 
    '#F5F5DC'
  ),
  (
    'Hematite', 
    'Grounds and protects us. It strengthens our connection with the earth.', 
    'Earth', 
    '#708090'
  ),
  (
    'Malachite', 
    'A stone of transformation. Assists in changing situations and spiritual growth.', 
    'Earth', 
    '#0BDA51'
  ),
  (
    'Labradorite', 
    'A stone of transformation, it is a useful companion through change, imparting strength and perseverance.', 
    'Water', 
    '#607C8E'
  ),
  (
    'Fluorite', 
    'Cleanses and stabilizes the aura. It absorbs and neutralizes negative energy and stress.', 
    'Air', 
    '#A020F0'
  ),
  (
    'Obsidian', 
    'A strongly protective stone, it forms a shield against negativity.', 
    'Fire', 
    '#1C1C1C'
  );


  -- Start interactions

  create table likes (
  user_id uuid references auth.users not null,
  post_id uuid references posts(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Composite Primary Key ensures unique likes per user per post
  primary key (user_id, post_id)
);

create table comments (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  post_id uuid references posts(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for performance when loading the feed
create index comments_post_id_idx on comments(post_id);

alter table likes enable row level security;
alter table comments enable row level security;

-- Polices for likes
-- 1. Everyone can view likes (needed to count them and show the heart icon)
create policy "Likes are viewable by everyone"
on likes for select
to authenticated, anon
using ( true );

-- 2. Authenticated users can insert their own like
create policy "Users can insert their own likes"
on likes for insert
to authenticated
with check ( auth.uid() = user_id );

-- 3. Users can delete (unlike) their own likes
create policy "Users can delete their own likes"
on likes for delete
to authenticated
using ( auth.uid() = user_id );

-- Policies for comments
-- 1. Everyone can view comments
create policy "Comments are viewable by everyone"
on comments for select
to authenticated, anon
using ( true );

-- 2. Authenticated users can create comments
create policy "Users can insert their own comments"
on comments for insert
to authenticated
with check ( auth.uid() = user_id );

-- 3. Users can delete their own comments
create policy "Users can delete their own comments"
on comments for delete
to authenticated
using ( auth.uid() = user_id );

-- 1. Ensure RLS is enabled
alter table comments enable row level security;

-- 2. Drop the old policy if it exists (to avoid conflicts)
drop policy if exists "Users can insert their own comments" on comments;

-- 3. Re-create the INSERT policy explicitly
create policy "Users can insert their own comments"
on comments for insert
to authenticated
with check ( auth.uid() = user_id );

-- 4. Double check the SELECT policy (so you can see what you posted)
drop policy if exists "Comments are viewable by everyone" on comments;
create policy "Comments are viewable by everyone"
on comments for select
to authenticated, anon
using ( true );

-- 1. Drop the old constraint that points to auth.users
-- (Note: The constraint name might vary, but 'comments_user_id_fkey' is the default)
alter table comments
drop constraint if exists comments_user_id_fkey;

-- 2. Add a new constraint that points explicitly to public.profiles
alter table comments
add constraint comments_user_id_fkey
foreign key (user_id)
references public.profiles (id)
on delete cascade;


-- Add a column to track when the user last 'grounded' their energy
alter table profiles 
add column last_read_notifications timestamptz default now();

-- 1. Ensure the column exists
alter table public.profiles 
add column if not exists created_at timestamp with time zone default timezone('utc'::text, now()) not null;

-- 2. Backfill: Copy the true signup date from auth.users to public.profiles
-- (This requires the query to run with admin privileges, which the SQL Editor has)
update public.profiles p
set created_at = a.created_at
from auth.users a
where p.id = a.id;


-- Add 'subtitle' column to profiles table
ALTER TABLE public.profiles 
ADD COLUMN subtitle TEXT DEFAULT '' NOT NULL;
ADD COLUMN bio TEXT DEFAULT '' NOT NULL;


create type element_type as enum ('Fire', 'Earth', 'Air', 'Water');
create type modality_type as enum ('Cardinal', 'Fixed', 'Mutable');

create table public.zodiac_signs (
  id uuid not null default gen_random_uuid (),
  created_at timestamptz not null default now(),
  name text not null unique,          -- e.g., "Aries"
  symbol text not null,               -- e.g., "♈" or an icon path
  element element_type not null,      -- Enum constraint
  modality modality_type not null,    -- Enum constraint
  ruling_planet text not null,        -- e.g., "Mars"
  description text not null,          -- Short summary
  keywords text[] not null,           -- Array of tags: ['Courageous', 'Impulsive']
  date_display text not null,         -- Display string: "March 21 - April 19"
  start_month int not null,           -- 3
  start_day int not null,             -- 21
  end_month int not null,             -- 4
  end_day int not null,               -- 19
  image_url text,                     -- Path to storage bucket
  constraint zodiac_signs_pkey primary key (id)
);

-- Enable Row Level Security (Public Read, Admin Write)
alter table public.zodiac_signs enable row level security;

create policy "Enable read access for all users" 
on public.zodiac_signs for select 
using (true);

-- 1. CLEANUP (Optional: Only run if you want to reset the table)
-- truncate table public.zodiac_signs restart identity;

-- 2. INSERT ALL 12 SIGNS
insert into public.zodiac_signs 
(name, element, modality, ruling_planet, start_month, start_day, end_month, end_day, symbol, description, keywords, date_display)
values 
(
  'Aries', 'Fire', 'Cardinal', 'Mars', 
  3, 21, 4, 19, 
  '♈', 
  'The bold pioneer of the zodiac. Aries energy is assertive, courageous, and direct. They blaze trails where others fear to tread.', 
  ARRAY['Courageous', 'Impulsive', 'Confident', 'Passionate'], 
  'March 21 - April 19'
),
(
  'Taurus', 'Earth', 'Fixed', 'Venus', 
  4, 20, 5, 20, 
  '♉', 
  'The grounded builder. Taurus values stability, beauty, and sensory pleasures. They are the anchor of the zodiac.', 
  ARRAY['Reliable', 'Patient', 'Devoted', 'Sensual'], 
  'April 20 - May 20'
),
(
  'Gemini', 'Air', 'Mutable', 'Mercury', 
  5, 21, 6, 20, 
  '♊', 
  'The cosmic messenger. Gemini is curious, adaptable, and quick-witted. They thrive on information and connection.', 
  ARRAY['Adaptable', 'Curious', 'Witty', 'Social'], 
  'May 21 - June 20'
),
(
  'Cancer', 'Water', 'Cardinal', 'Moon', 
  6, 21, 7, 22, 
  '♋', 
  'The intuitive protector. Cancer rules the emotional realm and the home. They deeply cherish family and emotional bonds.', 
  ARRAY['Intuitive', 'Protective', 'Sentimental', 'Nurturing'], 
  'June 21 - July 22'
),
(
  'Leo', 'Fire', 'Fixed', 'Sun', 
  7, 23, 8, 22, 
  '♌', 
  'The radiant king. Leo shines with creativity, passion, and leadership. They bring warmth and drama to the world.', 
  ARRAY['Charismatic', 'Generous', 'Creative', 'Proud'], 
  'July 23 - August 22'
),
(
  'Virgo', 'Earth', 'Mutable', 'Mercury', 
  8, 23, 9, 22, 
  '♍', 
  'The diligent perfectionist. Virgo seeks to improve the world through service, analysis, and practical skill.', 
  ARRAY['Analytical', 'Hardworking', 'Practical', 'Loyal'], 
  'August 23 - September 22'
),
(
  'Libra', 'Air', 'Cardinal', 'Venus', 
  9, 23, 10, 22, 
  '♎', 
  'The harmonizer. Libra seeks balance, justice, and beauty in all things. They are the masters of diplomacy.', 
  ARRAY['Diplomatic', 'Gracious', 'Fair-minded', 'Social'], 
  'September 23 - October 22'
),
(
  'Scorpio', 'Water', 'Fixed', 'Pluto', 
  10, 23, 11, 21, 
  '♏', 
  'The alchemist. Scorpio dives deep into the mysteries of life, transformation, and power. They are intense and magnetic.', 
  ARRAY['Passionate', 'Resourceful', 'Brave', 'Mysterious'], 
  'October 23 - November 21'
),
(
  'Sagittarius', 'Fire', 'Mutable', 'Jupiter', 
  11, 22, 12, 21, 
  '♐', 
  'The seeker. Sagittarius is on a quest for truth, adventure, and wisdom. They are the optimists of the zodiac.', 
  ARRAY['Optimistic', 'Adventurous', 'Philosophical', 'Honest'], 
  'November 22 - December 21'
),
(
  'Capricorn', 'Earth', 'Cardinal', 'Saturn', 
  12, 22, 1, 19, 
  '♑', 
  'The strategist. Capricorn climbs the mountain of success with discipline, patience, and ambition.', 
  ARRAY['Disciplined', 'Responsible', 'Ambitious', 'Patient'], 
  'December 22 - January 19'
),
(
  'Aquarius', 'Air', 'Fixed', 'Uranus', 
  1, 20, 2, 18, 
  '♒', 
  'The visionary. Aquarius marches to the beat of their own drum, focused on innovation, humanity, and the future.', 
  ARRAY['Original', 'Independent', 'Humanitarian', 'Intellectual'], 
  'January 20 - February 18'
),
(
  'Pisces', 'Water', 'Mutable', 'Neptune', 
  2, 19, 3, 20, 
  '♓', 
  'The dreamer. Pisces swims in the waters of imagination, empathy, and spirituality. They are the mystics.', 
  ARRAY['Compassionate', 'Artistic', 'Intuitive', 'Gentle'], 
  'February 19 - March 20'
);



-- 1. Add columns to the PUBLIC 'crystals' table
alter table public.crystals 
add column if not exists image_url text, -- The standard "Stock" image
add column if not exists color_category text; -- For the dropdown filter (e.g. 'Purple')

-- 2. Ensure the USER collection has their own image column
-- (We might have added this earlier, but this ensures it exists)
alter table public.user_crystal_collection
add column if not exists user_image_url text;

-- 3. SEED DATA: Update existing crystals with Categories and Unsplash Images
-- I have mapped these to real, high-quality public images.

-- Purple / Amethyst
update public.crystals set 
  color_category = 'Purple' 
where name = 'Amethyst';

-- Pink / Rose Quartz
update public.crystals set 
  color_category = 'Pink'
where name = 'Rose Quartz';

-- Clear / Clear Quartz
update public.crystals set 
  color_category = 'White' 
where name = 'Clear Quartz';

-- Black / Black Tourmaline
update public.crystals set 
  color_category = 'Black'
where name = 'Black Tourmaline';

-- Yellow / Citrine
update public.crystals set 
  color_category = 'Yellow' 
where name = 'Citrine';

-- White / Selenite
update public.crystals set 
  color_category = 'White' 
where name = 'Selenite';

-- Blue / Lapis Lazuli
update public.crystals set 
  color_category = 'Blue' 
where name = 'Lapis Lazuli';

-- Red / Carnelian
update public.crystals set 
  color_category = 'Red' 
where name = 'Carnelian';

-- Brown / Tiger's Eye
update public.crystals set 
  color_category = 'Brown' 
where name = 'Tiger''s Eye';

-- White / Moonstone
update public.crystals set 
  color_category = 'White'
where name = 'Moonstone';

-- Grey / Hematite
update public.crystals set 
  color_category = 'Grey'
where name = 'Hematite';

-- Green / Malachite
update public.crystals set 
  color_category = 'Green' 
where name = 'Malachite';

-- Blue / Labradorite
update public.crystals set 
  color_category = 'Blue' 
where name = 'Labradorite';

-- Purple / Fluorite
update public.crystals set 
  color_category = 'Purple'
where name = 'Fluorite';

-- Black / Obsidian
update public.crystals set 
  color_category = 'Black' 
where name = 'Obsidian';


-- Update crystals with dynamic placeholder images using their hex codes
-- Format: https://placehold.co/600x400/[HEX]/FFFFFF/png?text=[NAME]

update public.crystals set image_url = 'https://placehold.co/600x400/9966CC/FFFFFF/png?text=Amethyst' where name = 'Amethyst';
update public.crystals set image_url = 'https://placehold.co/600x400/F7C6C7/555555/png?text=Rose+Quartz' where name = 'Rose Quartz';
update public.crystals set image_url = 'https://placehold.co/600x400/E6E6E6/333333/png?text=Clear+Quartz' where name = 'Clear Quartz';
update public.crystals set image_url = 'https://placehold.co/600x400/1C1C1C/FFFFFF/png?text=Black+Tourmaline' where name = 'Black Tourmaline';
update public.crystals set image_url = 'https://placehold.co/600x400/E4D00A/333333/png?text=Citrine' where name = 'Citrine';
update public.crystals set image_url = 'https://placehold.co/600x400/FFFFFF/333333/png?text=Selenite' where name = 'Selenite';
update public.crystals set image_url = 'https://placehold.co/600x400/26619C/FFFFFF/png?text=Lapis+Lazuli' where name = 'Lapis Lazuli';
update public.crystals set image_url = 'https://placehold.co/600x400/B31B1B/FFFFFF/png?text=Carnelian' where name = 'Carnelian';
update public.crystals set image_url = 'https://placehold.co/600x400/E08D3C/FFFFFF/png?text=Tigers+Eye' where name = 'Tiger''s Eye';
update public.crystals set image_url = 'https://placehold.co/600x400/F5F5DC/333333/png?text=Moonstone' where name = 'Moonstone';
update public.crystals set image_url = 'https://placehold.co/600x400/708090/FFFFFF/png?text=Hematite' where name = 'Hematite';
update public.crystals set image_url = 'https://placehold.co/600x400/0BDA51/FFFFFF/png?text=Malachite' where name = 'Malachite';
update public.crystals set image_url = 'https://placehold.co/600x400/607C8E/FFFFFF/png?text=Labradorite' where name = 'Labradorite';
update public.crystals set image_url = 'https://placehold.co/600x400/A020F0/FFFFFF/png?text=Fluorite' where name = 'Fluorite';
update public.crystals set image_url = 'https://placehold.co/600x400/1C1C1C/FFFFFF/png?text=Obsidian' where name = 'Obsidian';

-- 1. Add the new columns
ALTER TABLE crystals 
ADD COLUMN zodiac TEXT,
ADD COLUMN chakra TEXT;

-- 2. Populate data for common crystals (Case insensitive matching)
UPDATE crystals SET zodiac = 'Pisces, Aquarius', chakra = 'Third Eye, Crown' WHERE name ILIKE 'Amethyst';
UPDATE crystals SET zodiac = 'Taurus, Libra', chakra = 'Heart' WHERE name ILIKE 'Rose Quartz';
UPDATE crystals SET zodiac = 'Leo, Sagittarius', chakra = 'Solar Plexus' WHERE name ILIKE 'Citrine';
UPDATE crystals SET zodiac = 'Scorpio, Capricorn', chakra = 'Root' WHERE name ILIKE 'Obsidian';
UPDATE crystals SET zodiac = 'Aries, Leo', chakra = 'Root' WHERE name ILIKE 'Carnelian';
UPDATE crystals SET zodiac = 'Gemini, Virgo', chakra = 'Throat' WHERE name ILIKE 'Blue Lace Agate';
UPDATE crystals SET zodiac = 'Cancer, Libra', chakra = 'Sacral' WHERE name ILIKE 'Moonstone';
UPDATE crystals SET zodiac = 'Virgo, Capricorn', chakra = 'Heart' WHERE name ILIKE 'Green Aventurine';
UPDATE crystals SET zodiac = 'Sagittarius, Virgo', chakra = 'Throat, Third Eye' WHERE name ILIKE 'Lapis Lazuli';
UPDATE crystals SET zodiac = 'Leo, Scorpio', chakra = 'Solar Plexus, Sacral' WHERE name ILIKE 'Tiger''s Eye';
UPDATE crystals SET zodiac = 'Gemini, Libra', chakra = 'All Chakras' WHERE name ILIKE 'Clear Quartz';
UPDATE crystals SET zodiac = 'Scorpio, Capricorn', chakra = 'Root' WHERE name ILIKE 'Smoky Quartz';
UPDATE crystals SET zodiac = 'Aries, Pisces', chakra = 'Root, Heart' WHERE name ILIKE 'Bloodstone';
UPDATE crystals SET zodiac = 'Taurus, Gemini', chakra = 'Heart, Throat' WHERE name ILIKE 'Chrysocolla';
UPDATE crystals SET zodiac = 'Leo, Libra', chakra = 'Heart' WHERE name ILIKE 'Rhodochrosite';
-- 1. Hematite: Grounding and mental clarity
UPDATE crystals 
SET zodiac = 'Aries, Aquarius', chakra = 'Root' 
WHERE name ILIKE 'Hematite';

-- 2. Selenite: Clarity and higher consciousness (Strongly linked to the Moon/Cancer)
UPDATE crystals 
SET zodiac = 'Cancer, Taurus', chakra = 'Crown, Third Eye' 
WHERE name ILIKE 'Selenite';

-- 3. Fluorite: Focus and order (Often linked to Capricorn for structure)
UPDATE crystals 
SET zodiac = 'Capricorn, Pisces', chakra = 'Heart, Throat, Third Eye' 
WHERE name ILIKE 'Fluorite';

-- 4. Black Tourmaline: The ultimate protection stone
UPDATE crystals 
SET zodiac = 'Capricorn, Libra', chakra = 'Root' 
WHERE name ILIKE 'Black Tourmaline';

-- 5. Malachite: Transformation and heart healing
UPDATE crystals 
SET zodiac = 'Scorpio, Capricorn', chakra = 'Heart, Solar Plexus' 
WHERE name ILIKE 'Malachite';

-- 6. Labradorite: Magic and intuition
UPDATE crystals 
SET zodiac = 'Leo, Scorpio, Sagittarius', chakra = 'Third Eye, Crown' 
WHERE name ILIKE 'Labradorite';


-- 1. Create the bucket (or update it to be PRIVATE if it already exists)
INSERT INTO storage.buckets (id, name, public)
VALUES ('user_uploads', 'user_uploads', false)
ON CONFLICT (id) DO UPDATE SET public = false;

-- 2. Clear out any old policies for this bucket to avoid conflicts
DROP POLICY IF EXISTS "Users can upload their own images" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can view images" ON storage.objects;
DROP POLICY IF EXISTS "Only owner can view images" ON storage.objects;

-- 3. Create the UPLOAD Policy (Authenticated users can upload their own files)
CREATE POLICY "Users can upload their own images" ON storage.objects
FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'user_uploads' AND auth.uid() = owner);

-- 4. Create the VIEW Policy (STRICT PRIVACY: Only the owner can view)
CREATE POLICY "Only owner can view images" ON storage.objects
FOR SELECT TO authenticated
USING (bucket_id = 'user_uploads' AND auth.uid() = owner);



-- 1. FIX PERMISSIONS (The most likely culprit)
alter table public.tarot_cards enable row level security;

-- Create a policy to let ANYONE read the cards
create policy "Public read access" 
on public.tarot_cards for select 
using (true);

-- 2. CHECK SCHEMA
-- This won't delete your data, but ensures the columns used for sorting exist.
-- If your columns are named differently (e.g., 'rank' instead of 'number'), 
-- you need to rename them or update the code to match your DB.

-- Example of renaming if you had 'type' instead of 'arcana':
-- alter table public.tarot_cards rename column type to arcana;

-- Add slug column if it doesn't exist
alter table public.tarot_cards add column if not exists slug text;

-- Auto-generate slugs from names (e.g. "Ace of Cups" -> "ace-of-cups")
update public.tarot_cards 
set slug = lower(replace(name, ' ', '-'))
where slug is null;




-- 1. KNOWLEDGE BASE TABLES
create table public.herbs (
  id uuid not null default gen_random_uuid (),
  name text not null unique,
  latin_name text,
  element text, -- Fire, Water, Air, Earth
  magical_uses text[], -- ['Protection', 'Luck']
  medical_uses text,
  description text,
  image_url text,
  constraint herbs_pkey primary key (id)
);

create table public.deities (
  id uuid not null default gen_random_uuid (),
  name text not null unique,
  pantheon text, -- e.g., 'Greek', 'Norse', 'Egyptian'
  domain text[], -- ['Underworld', 'Magic', 'Crossroads']
  symbols text[],
  description text,
  image_url text,
  constraint deities_pkey primary key (id)
);

create table public.candle_magic (
  id uuid not null default gen_random_uuid (),
  color text not null unique, -- 'Red', 'White', etc.
  hex_code text, -- For UI rendering: '#FF0000'
  associations text[], -- ['Passion', 'Strength']
  -- RELATIONSHIP: Links to the Zodiac ID
  zodiac_id uuid references public.zodiac_signs(id) on delete set null,
  description text,
  constraint candle_magic_pkey primary key (id)
);

-- 2. USER COLLECTION (SANCTUARY) TABLES
-- This tracks which items the specific user "owns" in their virtual inventory
create table public.user_herbs (
  id uuid not null default gen_random_uuid (),
  user_id uuid references auth.users(id) on delete cascade,
  herb_id uuid references public.herbs(id) on delete cascade,
  quantity int default 1,
  notes text,
  created_at timestamptz default now(),
  constraint user_herbs_pkey primary key (id)
);

create table public.user_deities (
  id uuid not null default gen_random_uuid (),
  user_id uuid references auth.users(id) on delete cascade,
  deity_id uuid references public.deities(id) on delete cascade,
  is_patron boolean default false, -- Special flag for their main deity
  created_at timestamptz default now(),
  constraint user_deities_pkey primary key (id)
);

create table public.user_candles (
  id uuid not null default gen_random_uuid (),
  user_id uuid references auth.users(id) on delete cascade,
  candle_id uuid references public.candle_magic(id) on delete cascade,
  quantity int default 1,
  created_at timestamptz default now(),
  constraint user_candles_pkey primary key (id)
);

-- 3. ENABLE RLS
alter table public.herbs enable row level security;
alter table public.deities enable row level security;
alter table public.candle_magic enable row level security;
alter table public.user_herbs enable row level security;
alter table public.user_deities enable row level security;
alter table public.user_candles enable row level security;

-- (Remember to add SELECT policies for Public info and ALL policies for User collections)

-- Seed Herbs
insert into public.herbs (name, element, magical_uses, medical_uses)
values 
('Lavender', 'Air', ARRAY['Peace', 'Sleep', 'Purification'], 'Anxiety and insomnia'),
('Rosemary', 'Fire', ARRAY['Memory', 'Protection', 'Healing'], 'Improved concentration');

-- Seed Deities
insert into public.deities (name, pantheon, domain, symbols)
values 
('Hecate', 'Greek', ARRAY['Magic', 'Crossroads', 'Ghosts'], ARRAY['Keys', 'Torches', 'Dogs']),
('Odin', 'Norse', ARRAY['Wisdom', 'War', 'Runes'], ARRAY['Ravens', 'Valknut', 'Spear']);

-- Seed Candles (Connecting to Zodiac)
-- Note: You'll need to check your zodiac_signs table for the actual IDs
insert into public.candle_magic (color, hex_code, associations, zodiac_id)
values 
('Red', '#ef4444', ARRAY['Passion', 'Action', 'Vitality'], (select id from zodiac_signs where name = 'Aries')),
('Blue', '#3b82f6', ARRAY['Communication', 'Truth', 'Peace'], (select id from zodiac_signs where name = 'Pisces'));

-- 1. Create the Planets Table
create table public.planets (
  id uuid not null default gen_random_uuid (),
  name text not null unique,          -- e.g., 'Mars'
  symbol text not null,               -- e.g., '♂'
  ruling_element text,                -- e.g., 'Fire'
  keywords text[],                    -- ['Action', 'Energy', 'Drive']
  description text,
  day_of_week text,                   -- e.g., 'Tuesday'
  image_url text,
  constraint planets_pkey primary key (id)
);

-- 2. Add Foreign Keys to existing tables to "Link" them
-- Link Zodiac to Planet (One Planet rules many Signs)
alter table public.zodiac_signs 
add column if not exists ruling_planet_id uuid references public.planets(id);

-- Link Candle Magic to Planet (One Planet rules many Colors)
alter table public.candle_magic 
add column if not exists planetary_id uuid references public.planets(id);

-- 3. Enable RLS
alter table public.planets enable row level security;
create policy "Public read access" on public.planets for select using (true);



-- Insert the 7 Traditional Planets
insert into public.planets (name, symbol, ruling_element, day_of_week, keywords, description)
values 
('Sun', '☉', 'Fire', 'Sunday', ARRAY['Self', 'Vitality', 'Spirit'], 'The center of our solar system, representing the core identity.'),
('Moon', '☾', 'Water', 'Monday', ARRAY['Emotions', 'Intuition', 'Unconscious'], 'The luminary of the night, governing our inner world.'),
('Mars', '♂', 'Fire', 'Tuesday', ARRAY['Action', 'Courage', 'Desire'], 'The red planet of drive and physical energy.'),
('Mercury', '☿', 'Air', 'Wednesday', ARRAY['Communication', 'Intellect', 'Travel'], 'The messenger, governing how we think and speak.'),
('Jupiter', '♃', 'Fire', 'Thursday', ARRAY['Expansion', 'Luck', 'Wisdom'], 'The planet of growth and opportunity.'),
('Venus', '♀', 'Earth', 'Friday', ARRAY['Love', 'Beauty', 'Harmony'], 'The planet of attraction and relationship.'),
('Saturn', '♄', 'Earth', 'Saturday', ARRAY['Structure', 'Discipline', 'Karma'], 'The taskmaster, governing limits and time.');

-- Link your existing Zodiac Signs to these new Planet IDs automatically!
update public.zodiac_signs set ruling_planet_id = (select id from planets where name = 'Mars') where name = 'Aries';
update public.zodiac_signs set ruling_planet_id = (select id from planets where name = 'Venus') where name = 'Taurus' or name = 'Libra';
update public.zodiac_signs set ruling_planet_id = (select id from planets where name = 'Mercury') where name = 'Gemini' or name = 'Virgo';
update public.zodiac_signs set ruling_planet_id = (select id from planets where name = 'Moon') where name = 'Cancer';
update public.zodiac_signs set ruling_planet_id = (select id from planets where name = 'Sun') where name = 'Leo';
update public.zodiac_signs set ruling_planet_id = (select id from planets where name = 'Jupiter') where name = 'Sagittarius';
update public.zodiac_signs set ruling_planet_id = (select id from planets where name = 'Saturn') where name = 'Capricorn';


-- Policies for 'herbs'
create policy "Allow public read access for herbs" 
on public.herbs for select using (true);

-- Policies for 'deities'
create policy "Allow public read access for deities" 
on public.deities for select using (true);

-- Policies for 'candle_magic'
create policy "Allow public read access for candles" 
on public.candle_magic for select using (true);

-- Policies for 'planets'
create policy "Allow public read access for planets" 
on public.planets for select using (true);


-- USER HERBS
create policy "Users can view their own herbs"
on public.user_herbs for select
using (auth.uid() = user_id);

create policy "Users can add to their own herbs"
on public.user_herbs for insert
with check (auth.uid() = user_id);

create policy "Users can update their own herbs"
on public.user_herbs for update
using (auth.uid() = user_id);

create policy "Users can remove from their own herbs"
on public.user_herbs for delete
using (auth.uid() = user_id);


-- USER DEITIES
create policy "Users can view their own deities"
on public.user_deities for select
using (auth.uid() = user_id);

create policy "Users can add to their own deities"
on public.user_deities for insert
with check (auth.uid() = user_id);

create policy "Users can remove from their own deities"
on public.user_deities for delete
using (auth.uid() = user_id);


-- USER CANDLES
create policy "Users can view their own candles"
on public.user_candles for select
using (auth.uid() = user_id);

create policy "Users can add to their own candles"
on public.user_candles for insert
with check (auth.uid() = user_id);

create policy "Users can update/delete their own candles"
on public.user_candles for all
using (auth.uid() = user_id);

-- 1. Add the columns
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS birth_date date,
ADD COLUMN IF NOT EXISTS zodiac_id uuid REFERENCES public.zodiac_signs(id);

-- 2. Performance (Optional but recommended): Index the zodiac_id for faster lookups
CREATE INDEX IF NOT EXISTS profiles_zodiac_id_idx ON public.profiles(zodiac_id);


-- UPDATE USER_HERBS
ALTER TABLE public.user_herbs
ADD COLUMN IF NOT EXISTS is_owned boolean default false,
ADD COLUMN IF NOT EXISTS is_wishlisted boolean default false,
ADD COLUMN IF NOT EXISTS user_image_url text;

-- UPDATE USER_DEITIES
ALTER TABLE public.user_deities
ADD COLUMN IF NOT EXISTS is_owned boolean default false,
ADD COLUMN IF NOT EXISTS is_wishlisted boolean default false,
ADD COLUMN IF NOT EXISTS user_image_url text;

-- UPDATE USER_CANDLES
ALTER TABLE public.user_candles
ADD COLUMN IF NOT EXISTS is_owned boolean default false,
ADD COLUMN IF NOT EXISTS is_wishlisted boolean default false,
ADD COLUMN IF NOT EXISTS user_image_url text;

-- (Optional) If you want to strictly match crystals, ensure you have is_owned boolean logic
-- Your existing tables imply "presence of row = owned", which works fine with the actions below.

INSERT INTO public.planets (name, symbol, ruling_element, keywords, description, day_of_week)
VALUES 
(
  'Uranus', 
  '♅', 
  'Air', 
  ARRAY['Change', 'Revolution', 'Innovation', 'Freedom'], 
  'The awakener. It breaks structures to create space for the new, governing sudden changes and rebellion.',
  NULL
),
(
  'Neptune', 
  '♆', 
  'Water', 
  ARRAY['Dreams', 'Intuition', 'Illusion', 'Spirituality'], 
  'The planet of inspiration and psychic receptivity. It dissolves boundaries between the self and the divine.',
  NULL
),
(
  'Pluto', 
  '♇', 
  'Water', -- Linked to Scorpio (Water)
  ARRAY['Transformation', 'Power', 'Rebirth', 'Shadow'], 
  'The planet of profound alchemy. It governs the cycle of death and rebirth, excavating what is hidden.',
  NULL
);



-- Link Aquarius to Uranus
UPDATE public.zodiac_signs 
SET ruling_planet_id = (SELECT id FROM public.planets WHERE name = 'Uranus') 
WHERE name = 'Aquarius';

-- Link Pisces to Neptune
UPDATE public.zodiac_signs 
SET ruling_planet_id = (SELECT id FROM public.planets WHERE name = 'Neptune') 
WHERE name = 'Pisces';

-- Link Scorpio to Pluto
UPDATE public.zodiac_signs 
SET ruling_planet_id = (SELECT id FROM public.planets WHERE name = 'Pluto') 
WHERE name = 'Scorpio';

-- Removed normal text column and replaced with ID to other data set for planets
ALTER TABLE public.zodiac_signs 
DROP COLUMN ruling_planet;




-- 1. Drop the old/messy policies on user_candles
DROP POLICY IF EXISTS "Users can update/delete their own candles" ON user_candles;
DROP POLICY IF EXISTS "Users can add to their own candles" ON user_candles;
DROP POLICY IF EXISTS "Users can view their own candles" ON user_candles;

-- 2. Create standard policies (Mirroring user_crystal_collection)

-- SELECT
CREATE POLICY "Users can view their own candles"
ON user_candles FOR SELECT
USING ( auth.uid() = user_id );

-- INSERT
CREATE POLICY "Users can add to their own candles"
ON user_candles FOR INSERT
WITH CHECK ( auth.uid() = user_id );

-- UPDATE
CREATE POLICY "Users can update their own candles"
ON user_candles FOR UPDATE
USING ( auth.uid() = user_id )
WITH CHECK ( auth.uid() = user_id );

-- DELETE
CREATE POLICY "Users can remove from their own candles"
ON user_candles FOR DELETE
USING ( auth.uid() = user_id );




-- 1. Add Unique Constraint for Candles
ALTER TABLE user_candles 
ADD CONSTRAINT user_candles_unique_pair UNIQUE (user_id, candle_id);

-- 2. Add Unique Constraint for Herbs
-- (Assuming your column is named 'herb_id')
ALTER TABLE user_herbs 
ADD CONSTRAINT user_herbs_unique_pair UNIQUE (user_id, herb_id);

-- 3. Add Unique Constraint for Deities
-- (Assuming your column is named 'deity_id')
ALTER TABLE user_deities 
ADD CONSTRAINT user_deities_unique_pair UNIQUE (user_id, deity_id);




-- === HERBS: Reset & Standardize ===
DROP POLICY IF EXISTS "Users can remove from their own herbs" ON user_herbs;
DROP POLICY IF EXISTS "Users can add to their own herbs" ON user_herbs;
DROP POLICY IF EXISTS "Users can view their own herbs" ON user_herbs;
DROP POLICY IF EXISTS "Users can update their own herbs" ON user_herbs;

CREATE POLICY "Users can view their own herbs" ON user_herbs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can add to their own herbs" ON user_herbs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own herbs" ON user_herbs FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can remove from their own herbs" ON user_herbs FOR DELETE USING (auth.uid() = user_id);

-- === DEITIES: Reset & Standardize ===
DROP POLICY IF EXISTS "Users can remove from their own deities" ON user_deities;
DROP POLICY IF EXISTS "Users can add to their own deities" ON user_deities;
DROP POLICY IF EXISTS "Users can view their own deities" ON user_deities;
DROP POLICY IF EXISTS "Users can update their own deities" ON user_deities;

CREATE POLICY "Users can view their own deities" ON user_deities FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can add to their own deities" ON user_deities FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own deities" ON user_deities FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can remove from their own deities" ON user_deities FOR DELETE USING (auth.uid() = user_id);

ALTER TABLE user_crystal_collection RENAME TO user_crystals;