-- 1. Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  
  -- Custom witchy fields
  moon_phase text, 
  coven_name text,

  constraint username_length check (char_length(username) >= 3)
);

-- 2. Enable Row Level Security (RLS)
-- This turns on the security system so random people can't delete your data.
alter table profiles enable row level security;

-- 3. Create Policy: "Public profiles are viewable by everyone."
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

-- 4. Create Policy: "Users can insert their own profile."
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

-- 5. Create Policy: "Users can update own profile."
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

  -- 1. Create a function that inserts a row into public.profiles
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, full_name)
  values (
    new.id, 
    new.email, -- defaults username to email initially
    new.raw_user_meta_data ->> 'full_name'
  );
  return new;
end;
$$;

-- 2. Create the trigger to fire that function every time a user signs up
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

  -- 1. ADD ROLES TO PROFILES
-- We add a 'role' column. Default is 'initiate' (non-verified).
-- Future values could be: 'verified', 'supporter', 'admin'.
ALTER TABLE public.profiles 
ADD COLUMN role text default 'initiate';

-- 2. CREATE POSTS TABLE
create table public.posts (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  image_url text, -- Optional image for the post
  
  -- Link the post to the User who wrote it
  user_id uuid references public.profiles(id) not null
);

-- 3. ENABLE SECURITY (RLS)
alter table public.posts enable row level security;

-- 4. POLICIES
-- Everyone can SEE posts
create policy "Public posts are viewable by everyone."
  on public.posts for select
  using ( true );

-- Only Logged In users can CREATE posts
create policy "Authenticated users can insert posts"
  on public.posts for insert
  with check ( auth.uid() = user_id );

-- Users can only DELETE their OWN posts
create policy "Users can delete own posts"
  on public.posts for delete
  using ( auth.uid() = user_id );

  -- 1. Add a handle column
ALTER TABLE public.profiles 
ADD COLUMN handle text unique;

-- 2. Populate existing handles (temporary fix for existing users)
-- This just takes their username and makes it lowercase.
UPDATE public.profiles 
SET handle = lower(replace(username, ' ', '-'));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, handle, full_name)
  values (
    new.id, 
    -- 1. Get the username passed from the Sign Up form
    new.raw_user_meta_data ->> 'username',
    -- 2. Get the handle passed (or generate one if missing)
    new.raw_user_meta_data ->> 'handle',
    -- 3. Full name if provided
    new.raw_user_meta_data ->> 'full_name'
  );
  return new;
end;
$$;

  -- Create a table for Tarot Cards
create table tarot_cards (
  id bigint generated by default as identity primary key,
  name text not null,
  suit text, -- 'Wands', 'Cups', 'Swords', 'Pentacles', or null for Major Arcana
  arcana_type text not null, -- 'Major' or 'Minor'
  meaning_upright text,
  meaning_reversed text,
  description text,
  image_url text -- Optional: You can add links to card images later
);

-- Enable Row Level Security (RLS) so everyone can READ, but only you can WRITE
alter table tarot_cards enable row level security;

create policy "Tarot cards are viewable by everyone"
  on tarot_cards for select
  using ( true );

ALTER TABLE tarot_cards
  ADD COLUMN element TEXT,
  ADD COLUMN astrology TEXT,
  ADD COLUMN numerical_keyword TEXT;

-- 1. INSERT MAJOR ARCANA
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('The Fool', NULL, 'Major', 'Beginnings, innocence, spontaneity, free spirit', 'Hesitation, reckless choices, risk without thought', NULL, 'Air', 'Uranus', '0 — Infinite potential'),
('The Magician', NULL, 'Major', 'Manifestation, resourcefulness, inspired action', 'Manipulation, unused potential, deception', NULL, 'Air', 'Mercury', '1 — Action, willpower'),
('The High Priestess', NULL, 'Major', 'Intuition, subconscious knowledge, mystery', 'Secrets, disconnection, blocked intuition', NULL, 'Water', 'Moon', '2 — Duality, hidden truths'),
('The Empress', NULL, 'Major', 'Abundance, nurturing, creativity, fertility', 'Dependence, creative blocks, smothering energy', NULL, 'Earth', 'Venus', '3 — Growth, creation'),
('The Emperor', NULL, 'Major', 'Authority, structure, discipline, power', 'Tyranny, rigidity, lack of control', NULL, 'Fire', 'Aries', '4 — Stability, foundation'),
('The Hierophant', NULL, 'Major', 'Tradition, spiritual wisdom, conformity', 'Rebellion, challenge of norms, personal beliefs', NULL, 'Earth', 'Taurus', '5 — Teaching, structure'),
('The Lovers', NULL, 'Major', 'Love, harmony, choices, alignment', 'Imbalance, disharmony, difficult choices', NULL, 'Air', 'Gemini', '6 — Union, relationships'),
('The Chariot', NULL, 'Major', 'Willpower, victory, determination', 'Lack of control, scattered energy, defeat', NULL, 'Water', 'Cancer', '7 — Direction, mastery'),
('Strength', NULL, 'Major', 'Inner strength, courage, compassion', 'Self-doubt, insecurity, weakness', NULL, 'Fire', 'Leo', '8 — Power, resilience'),
('The Hermit', NULL, 'Major', 'Soul-searching, introspection, solitude', 'Isolation, loneliness, distraction', NULL, 'Earth', 'Virgo', '9 — Wisdom, searching'),
('Wheel of Fortune', NULL, 'Major', 'Luck, fate, cycles, turning point', 'Bad luck, resistance to change', NULL, 'Fire', 'Jupiter', '10 — Change, destiny'),
('Justice', NULL, 'Major', 'Truth, fairness, law, cause and effect', 'Unfairness, dishonesty, imbalance', NULL, 'Air', 'Libra', '11 — Balance, truth'),
('The Hanged Man', NULL, 'Major', 'Sacrifice, release, new perspective', 'Stagnation, delay, refusal to let go', NULL, 'Water', 'Neptune', '12 — Surrender, pause'),
('Death', NULL, 'Major', 'Transformation, endings, transition', 'Resistance to change, stagnation', NULL, 'Water', 'Scorpio', '13 — Rebirth, cycles'),
('Temperance', NULL, 'Major', 'Balance, moderation, harmony', 'Imbalance, excess, conflict', NULL, 'Fire', 'Sagittarius', '14 — Healing, blending'),
('The Devil', NULL, 'Major', 'Bondage, addiction, temptation', 'Release, freedom, detachment', NULL, 'Earth', 'Capricorn', '15 — Shadow self'),
('The Tower', NULL, 'Major', 'Sudden change, upheaval, revelation', 'Avoidance, fear of change, delay', NULL, 'Fire', 'Mars', '16 — Ruin, awakening'),
('The Star', NULL, 'Major', 'Hope, inspiration, renewal', 'Despair, lack of faith, discouragement', NULL, 'Air', 'Aquarius', '17 — Guidance, clarity'),
('The Moon', NULL, 'Major', 'Illusion, fear, subconscious', 'Clarity, truth revealed, release of fear', NULL, 'Water', 'Pisces', '18 — Dreams, intuition'),
('The Sun', NULL, 'Major', 'Joy, success, vitality, positivity', 'Temporary sadness, lack of clarity', NULL, 'Fire', 'Sun', '19 — Radiance, growth'),
('Judgement', NULL, 'Major', 'Awakening, renewal, purpose', 'Self-doubt, stagnation, ignoring calling', NULL, 'Fire', 'Pluto', '20 — Reckoning, truth'),
('The World', NULL, 'Major', 'Completion, wholeness, accomplishment', 'Incomplete goals, delays, stagnation', NULL, 'Earth', 'Saturn', '21 — Completion, mastery');

-- 2. INSERT WANDS
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('Ace of Wands', 'Wands', 'Minor', 'Inspiration, creation, new energy', 'Delays, lack of direction', NULL, 'Fire', 'Aries/Leo/Sagittarius', '1 — Potential'),
('Two of Wands', 'Wands', 'Minor', 'Planning, decisions, future vision', 'Fear of change, bad planning', NULL, 'Fire', 'Mars in Aries', '2 — Duality'),
('Three of Wands', 'Wands', 'Minor', 'Expansion, foresight, progress', 'Delays, obstacles, disappointment', NULL, 'Fire', 'Sun in Aries', '3 — Growth'),
('Four of Wands', 'Wands', 'Minor', 'Celebration, harmony, home', 'Conflict at home, instability', NULL, 'Fire', 'Venus in Aries', '4 — Stability'),
('Five of Wands', 'Wands', 'Minor', 'Conflict, competition, tension', 'Avoiding conflict, inner tension', NULL, 'Fire', 'Saturn in Leo', '5 — Struggle'),
('Six of Wands', 'Wands', 'Minor', 'Victory, success, recognition', 'Ego, fall from grace, delays', NULL, 'Fire', 'Jupiter in Leo', '6 — Triumph'),
('Seven of Wands', 'Wands', 'Minor', 'Defense, perseverance', 'Exhaustion, giving up', NULL, 'Fire', 'Mars in Leo', '7 — Challenge'),
('Eight of Wands', 'Wands', 'Minor', 'Movement, fast action', 'Delays, frustration', NULL, 'Fire', 'Mercury in Sagittarius', '8 — Acceleration'),
('Nine of Wands', 'Wands', 'Minor', 'Resilience, boundaries', 'Paranoia, overwhelm', NULL, 'Fire', 'Moon in Sagittarius', '9 — Persistence'),
('Ten of Wands', 'Wands', 'Minor', 'Burden, hard work', 'Burnout, release needed', NULL, 'Fire', 'Saturn in Sagittarius', '10 — Completion'),
('Page of Wands', 'Wands', 'Minor', 'Exploration, enthusiasm', 'Lack of direction, immaturity', NULL, 'Fire', 'Fire Signs', 'Youthful Fire'),
('Knight of Wands', 'Wands', 'Minor', 'Action, passion, adventure', 'Recklessness, impatience', NULL, 'Fire', 'Fire Signs', 'Young Fire'),
('Queen of Wands', 'Wands', 'Minor', 'Confidence, determination', 'Jealousy, insecurity', NULL, 'Fire', 'Aries', 'Mature Fire'),
('King of Wands', 'Wands', 'Minor', 'Leadership, vision', 'Impulsiveness, domineering', NULL, 'Fire', 'Leo', 'Mastery of Fire');

-- 3. INSERT CUPS
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('Ace of Cups', 'Cups', 'Minor', 'Love, new feelings, compassion', 'Blocked emotions, emptiness', NULL, 'Water', 'Cancer/Scorpio/Pisces', '1 — Emotional potential'),
('Two of Cups', 'Cups', 'Minor', 'Union, partnership, connection', 'Breakup, imbalance', NULL, 'Water', 'Venus in Cancer', '2 — Unity'),
('Three of Cups', 'Cups', 'Minor', 'Friendship, community', 'Overindulgence, isolation', NULL, 'Water', 'Mercury in Cancer', '3 — Community'),
('Four of Cups', 'Cups', 'Minor', 'Apathy, contemplation', 'Awareness, acceptance', NULL, 'Water', 'Moon in Cancer', '4 — Withdrawal'),
('Five of Cups', 'Cups', 'Minor', 'Grief, disappointment', 'Acceptance, healing', NULL, 'Water', 'Mars in Scorpio', '5 — Loss'),
('Six of Cups', 'Cups', 'Minor', 'Nostalgia, innocence', 'Stuck in past, naivety', NULL, 'Water', 'Sun in Scorpio', '6 — Memory'),
('Seven of Cups', 'Cups', 'Minor', 'Choices, fantasy, illusion', 'Clarity, groundedness', NULL, 'Water', 'Venus in Scorpio', '7 — Illusion'),
('Eight of Cups', 'Cups', 'Minor', 'Walking away, deeper purpose', 'Avoidance, fear of change', NULL, 'Water', 'Saturn in Pisces', '8 — Departure'),
('Nine of Cups', 'Cups', 'Minor', 'Contentment, satisfaction', 'Greed, dissatisfaction', NULL, 'Water', 'Jupiter in Pisces', '9 — Fulfillment'),
('Ten of Cups', 'Cups', 'Minor', 'Harmony, bliss, family', 'Disconnection, misalignment', NULL, 'Water', 'Mars in Pisces', '10 — Emotional completion'),
('Page of Cups', 'Cups', 'Minor', 'Creativity, curiosity', 'Emotional immaturity', NULL, 'Water', 'Water Signs', 'Youthful Water'),
('Knight of Cups', 'Cups', 'Minor', 'Romance, idealism', 'Moodiness, unrealistic', NULL, 'Water', 'Water Signs', 'Young Water'),
('Queen of Cups', 'Cups', 'Minor', 'Compassion, intuition', 'Codependency', NULL, 'Water', 'Cancer', 'Mature Water'),
('King of Cups', 'Cups', 'Minor', 'Balance, wisdom, control', 'Coldness, manipulation', NULL, 'Water', 'Scorpio', 'Mastery of Water');

-- 4. INSERT SWORDS
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('Ace of Swords', 'Swords', 'Minor', 'Breakthrough, clarity', 'Confusion, chaos', NULL, 'Air', 'Gemini/Libra/Aquarius', '1 — Mental clarity'),
('Two of Swords', 'Swords', 'Minor', 'Indecision, stalemate', 'Truth revealed, decision made', NULL, 'Air', 'Moon in Libra', '2 — Block'),
('Three of Swords', 'Swords', 'Minor', 'Heartbreak, grief', 'Recovery, forgiveness', NULL, 'Air', 'Saturn in Libra', '3 — Pain'),
('Four of Swords', 'Swords', 'Minor', 'Rest, restoration', 'Burnout, restlessness', NULL, 'Air', 'Jupiter in Libra', '4 — Recovery'),
('Five of Swords', 'Swords', 'Minor', 'Conflict, betrayal', 'Resolution, compromise', NULL, 'Air', 'Venus in Aquarius', '5 — Defeat'),
('Six of Swords', 'Swords', 'Minor', 'Transition, healing', 'Trouble, resistance', NULL, 'Air', 'Mercury in Aquarius', '6 — Passage'),
('Seven of Swords', 'Swords', 'Minor', 'Deception, strategy', 'Confession, truth', NULL, 'Air', 'Moon in Aquarius', '7 — Strategy'),
('Eight of Swords', 'Swords', 'Minor', 'Restriction, fear', 'Freedom, release', NULL, 'Air', 'Jupiter in Gemini', '8 — Limitation'),
('Nine of Swords', 'Swords', 'Minor', 'Anxiety, worry', 'Relief, hope', NULL, 'Air', 'Mars in Gemini', '9 — Despair'),
('Ten of Swords', 'Swords', 'Minor', 'Endings, collapse', 'Recovery, regeneration', NULL, 'Air', 'Sun in Gemini', '10 — Finality'),
('Page of Swords', 'Swords', 'Minor', 'Curiosity, new ideas', 'Deception, manipulation', NULL, 'Air', 'Air Signs', 'Youthful Air'),
('Knight of Swords', 'Swords', 'Minor', 'Speed, ambition', 'Aggression, recklessness', NULL, 'Air', 'Air Signs', 'Young Air'),
('Queen of Swords', 'Swords', 'Minor', 'Independence, clarity', 'Coldness, bitterness', NULL, 'Air', 'Libra', 'Mature Air'),
('King of Swords', 'Swords', 'Minor', 'Discipline, truth', 'Manipulation, cruelty', NULL, 'Air', 'Aquarius', 'Mastery of Air');

-- 5. INSERT PENTACLES
INSERT INTO public.tarot_cards (name, suit, arcana_type, meaning_upright, meaning_reversed, description, element, astrology, numerical_keyword) VALUES 
('Ace of Pentacles', 'Pentacles', 'Minor', 'Opportunity, prosperity', 'Lost opportunity', NULL, 'Earth', 'Taurus/Virgo/Capricorn', '1 — Material potential'),
('Two of Pentacles', 'Pentacles', 'Minor', 'Balance, adaptability', 'Disorganization', NULL, 'Earth', 'Jupiter in Capricorn', '2 — Balance'),
('Three of Pentacles', 'Pentacles', 'Minor', 'Teamwork, mastery', 'Disharmony', NULL, 'Earth', 'Mars in Capricorn', '3 — Collaboration'),
('Four of Pentacles', 'Pentacles', 'Minor', 'Security, control', 'Greed, releasing control', NULL, 'Earth', 'Sun in Capricorn', '4 — Possession'),
('Five of Pentacles', 'Pentacles', 'Minor', 'Poverty, hardship', 'Recovery, assistance', NULL, 'Earth', 'Mercury in Taurus', '5 — Loss'),
('Six of Pentacles', 'Pentacles', 'Minor', 'Generosity, giving', 'Strings attached', NULL, 'Earth', 'Moon in Taurus', '6 — Exchange'),
('Seven of Pentacles', 'Pentacles', 'Minor', 'Patience, investment', 'Impatience, waste', NULL, 'Earth', 'Saturn in Taurus', '7 — Evaluation'),
('Eight of Pentacles', 'Pentacles', 'Minor', 'Skill, hard work', 'Perfectionism, lack of focus', NULL, 'Earth', 'Sun in Virgo', '8 — Work'),
('Nine of Pentacles', 'Pentacles', 'Minor', 'Luxury, self-sufficiency', 'Overinvestment', NULL, 'Earth', 'Venus in Virgo', '9 — Reward'),
('Ten of Pentacles', 'Pentacles', 'Minor', 'Wealth, family legacy', 'Financial failure', NULL, 'Earth', 'Mercury in Virgo', '10 — Legacy'),
('Page of Pentacles', 'Pentacles', 'Minor', 'Ambition, opportunity', 'Procrastination', NULL, 'Earth', 'Earth Signs', 'Youthful Earth'),
('Knight of Pentacles', 'Pentacles', 'Minor', 'Routine, efficiency', 'Laziness, stagnation', NULL, 'Earth', 'Earth Signs', 'Young Earth'),
('Queen of Pentacles', 'Pentacles', 'Minor', 'Practicality, comfort', 'Smothering, jealousy', NULL, 'Earth', 'Capricorn', 'Mature Earth'),
('King of Pentacles', 'Pentacles', 'Minor', 'Abundance, control', 'Greed, stubbornness', NULL, 'Earth', 'Taurus', 'Mastery of Earth');

create table user_daily_tarot (
  user_id uuid references auth.users not null primary key,
  
  -- Logic for the 3-Card Spread Page
  spread_date date, -- The date this spread was drawn
  spread_card_ids bigint[], -- Array of 3 IDs drawn for the spread
  
  -- Logic for the Widget (Deck draining)
  widget_date date, -- The date the widget deck was last touched
  widget_drawn_ids bigint[], -- Array of IDs ALREADY drawn today
  
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table user_daily_tarot enable row level security;

-- Policy: Users can only read/update their own data
create policy "Users can view own tarot data" on user_daily_tarot
  for select using (auth.uid() = user_id);

create policy "Users can update own tarot data" on user_daily_tarot
  for update using (auth.uid() = user_id);

create policy "Users can insert own tarot data" on user_daily_tarot
  for insert with check (auth.uid() = user_id);

-- Create a table for Spells
create table spells (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  
  title text not null,
  intent text, -- e.g. "Protection", "Love", "Wealth"
  ingredients text, -- Simple text for now, can be JSON later
  moon_phase text, -- e.g. "Waxing", "Full"
  content text, -- The actual steps/description
  is_private boolean default true, -- Default to private
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Security
alter table spells enable row level security;

-- Policies
create policy "Public spells are viewable by everyone" on spells
  for select using (
    -- Rule: You are the owner OR the spell is not private
    auth.uid() = user_id OR is_private = false
  );

create policy "Users can insert own spells" on spells
  for insert with check (auth.uid() = user_id);

create policy "Users can update own spells" on spells
  for update using (auth.uid() = user_id);

create policy "Users can delete own spells" on spells
  for delete using (auth.uid() = user_id);

-- Create a table for Altar Items
create table altar_items (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  
  item_type text not null, -- 'candle', 'crystal', 'incense'
  variant text, -- 'white_candle', 'amethyst', etc.
  
  position_x integer default 50, -- For future drag-and-drop (percentage 0-100)
  position_y integer default 50, -- For future drag-and-drop
  
  active_since timestamp with time zone, -- When the candle was lit
  duration_minutes integer, -- How long it lasts (e.g., 1440 for 24 hours)
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table altar_items enable row level security;

-- Policies
create policy "Users can manage own altar" on altar_items
  for all using (auth.uid() = user_id);